version: "3"
services:
  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - ./config/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    links:
      - "gitlab:gitlab.localhost.com"
    depends_on:
      - gitlab
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: "gitlab"
    restart: always
    hostname: "gitlab.localhost.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost.com'
        unicorn['worker_timeout'] = 120
        unicorn['worker_processes'] = 2
    ports:
      - 80:80
      - 443:443
      - 22:22
    networks:
      default:
        aliases:
          - gitlab.localhost.com
    volumes:
      - ./config/gitlab:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: "bridge"
